# Placeholders for Python SDK functions to be wrapped

login <- function() {}
logout <- function() {}
news <- function() {}
whoami <- function() {}
alt.about <- function() {}
alt.hn <- function() {}
alt.hn_chart <- function() {}
alt.covid.about <- function() {}
alt.covid.global_cases <- function() {}
alt.covid.global_deaths <- function() {}
alt.covid.ov <- function() {}
alt.covid.ov_chart <- function() {}
alt.covid.slopes <- function() {}
alt.covid.slopes_chart <- function() {}
alt.covid.stat <- function() {}
alt.covid.stat_chart <- function() {}
alt.oss.about <- function() {}
alt.oss.github_data <- function() {}
alt.oss.history <- function() {}
alt.oss.history_chart <- function() {}
alt.oss.ross <- function() {}
alt.oss.ross_chart <- function() {}
alt.oss.search <- function() {}
alt.oss.summary <- function() {}
alt.oss.summary_chart <- function() {}
alt.oss.top <- function() {}
alt.oss.top_chart <- function() {}
alt.realestate.about <- function() {}
alt.realestate.get_estate_sales <- function() {}
alt.realestate.get_region_stats <- function() {}
alt.realestate.get_towns_sold_prices <- function() {}
crypto.about <- function() {}
crypto.candle <- function() {}
crypto.chart <- function() {}
crypto.find <- function() {}
crypto.load <- function() {}
crypto.price <- function() {}
crypto.dd.about <- function() {}
crypto.dd.active <- function() {}
crypto.dd.active_chart <- function() {}
crypto.dd.all_binance_trading_pairs <- function() {}
crypto.dd.ath <- function() {}
crypto.dd.atl <- function() {}
crypto.dd.balance <- function() {}
crypto.dd.balance_chart <- function() {}
crypto.dd.basic <- function() {}
crypto.dd.basic_chart <- function() {}
crypto.dd.binance_available_quotes_for_each_coin <- function() {}
crypto.dd.candle <- function() {}
crypto.dd.change <- function() {}
crypto.dd.change_chart <- function() {}
crypto.dd.check_valid_binance_str <- function() {}
crypto.dd.close <- function() {}
crypto.dd.coin <- function() {}
crypto.dd.coin_market_chart <- function() {}
crypto.dd.dev <- function() {}
crypto.dd.eb <- function() {}
crypto.dd.eb_chart <- function() {}
crypto.dd.events <- function() {}
crypto.dd.events_chart <- function() {}
crypto.dd.ex <- function() {}
crypto.dd.ex_chart <- function() {}
crypto.dd.exchanges <- function() {}
crypto.dd.fr <- function() {}
crypto.dd.fr_chart <- function() {}
crypto.dd.get_mt <- function() {}
crypto.dd.get_mt_chart <- function() {}
crypto.dd.gh <- function() {}
crypto.dd.gh_chart <- function() {}
crypto.dd.gov <- function() {}
crypto.dd.gov_chart <- function() {}
crypto.dd.headlines <- function() {}
crypto.dd.headlines_chart <- function() {}
crypto.dd.inv <- function() {}
crypto.dd.inv_chart <- function() {}
crypto.dd.links <- function() {}
crypto.dd.links_chart <- function() {}
crypto.dd.mcapdom <- function() {}
crypto.dd.mcapdom_chart <- function() {}
crypto.dd.mkt <- function() {}
crypto.dd.mkt_chart <- function() {}
crypto.dd.mt <- function() {}
crypto.dd.mt_chart <- function() {}
crypto.dd.news <- function() {}
crypto.dd.news_chart <- function() {}
crypto.dd.nonzero <- function() {}
crypto.dd.nonzero_chart <- function() {}
crypto.dd.ob <- function() {}
crypto.dd.ob_chart <- function() {}
crypto.dd.oi <- function() {}
crypto.dd.oi_chart <- function() {}
crypto.dd.pi <- function() {}
crypto.dd.pi_chart <- function() {}
crypto.dd.pr <- function() {}
crypto.dd.pr_chart <- function() {}
crypto.dd.ps <- function() {}
crypto.dd.ps_chart <- function() {}
crypto.dd.rm <- function() {}
crypto.dd.rm_chart <- function() {}
crypto.dd.score <- function() {}
crypto.dd.show_available_pairs_for_given_symbol <- function() {}
crypto.dd.social <- function() {}
crypto.dd.stats <- function() {}
crypto.dd.stats_chart <- function() {}
crypto.dd.team <- function() {}
crypto.dd.team_chart <- function() {}
crypto.dd.tk <- function() {}
crypto.dd.tk_chart <- function() {}
crypto.dd.tokenomics <- function() {}
crypto.dd.trades <- function() {}
crypto.dd.trades_chart <- function() {}
crypto.dd.trading_pair_info <- function() {}
crypto.dd.trading_pairs <- function() {}
crypto.dd.twitter <- function() {}
crypto.dd.twitter_chart <- function() {}
crypto.defi.about <- function() {}
crypto.defi.anchor_data <- function() {}
crypto.defi.anchor_data_chart <- function() {}
crypto.defi.aterra <- function() {}
crypto.defi.aterra_chart <- function() {}
crypto.defi.ayr <- function() {}
crypto.defi.ayr_chart <- function() {}
crypto.defi.dtvl <- function() {}
crypto.defi.dtvl_chart <- function() {}
crypto.defi.gacc <- function() {}
crypto.defi.gacc_chart <- function() {}
crypto.defi.gdapps <- function() {}
crypto.defi.gdapps_chart <- function() {}
crypto.defi.gov_proposals <- function() {}
crypto.defi.gov_proposals_chart <- function() {}
crypto.defi.ldapps <- function() {}
crypto.defi.ldapps_chart <- function() {}
crypto.defi.luna_supply <- function() {}
crypto.defi.luna_supply_chart <- function() {}
crypto.defi.newsletters <- function() {}
crypto.defi.newsletters_chart <- function() {}
crypto.defi.pairs <- function() {}
crypto.defi.pairs_chart <- function() {}
crypto.defi.pools <- function() {}
crypto.defi.pools_chart <- function() {}
crypto.defi.sinfo <- function() {}
crypto.defi.sinfo_chart <- function() {}
crypto.defi.sratio <- function() {}
crypto.defi.sratio_chart <- function() {}
crypto.defi.sreturn <- function() {}
crypto.defi.sreturn_chart <- function() {}
crypto.defi.stats <- function() {}
crypto.defi.stats_chart <- function() {}
crypto.defi.stvl <- function() {}
crypto.defi.stvl_chart <- function() {}
crypto.defi.swaps <- function() {}
crypto.defi.swaps_chart <- function() {}
crypto.defi.tokens <- function() {}
crypto.defi.tokens_chart <- function() {}
crypto.defi.validators <- function() {}
crypto.defi.validators_chart <- function() {}
crypto.defi.vaults <- function() {}
crypto.defi.vaults_chart <- function() {}
crypto.disc.about <- function() {}
crypto.disc.categories_keys <- function() {}
crypto.disc.coin_list <- function() {}
crypto.disc.coins <- function() {}
crypto.disc.coins_chart <- function() {}
crypto.disc.coins_for_given_exchange <- function() {}
crypto.disc.cpsearch <- function() {}
crypto.disc.cpsearch_chart <- function() {}
crypto.disc.gainers <- function() {}
crypto.disc.gainers_chart <- function() {}
crypto.disc.losers <- function() {}
crypto.disc.losers_chart <- function() {}
crypto.disc.top_coins <- function() {}
crypto.disc.top_dapps <- function() {}
crypto.disc.top_dapps_chart <- function() {}
crypto.disc.top_dexes <- function() {}
crypto.disc.top_dexes_chart <- function() {}
crypto.disc.top_games <- function() {}
crypto.disc.top_games_chart <- function() {}
crypto.disc.top_nfts <- function() {}
crypto.disc.top_nfts_chart <- function() {}
crypto.disc.trending <- function() {}
crypto.disc.trending_chart <- function() {}
crypto.nft.about <- function() {}
crypto.nft.collections <- function() {}
crypto.nft.collections_chart <- function() {}
crypto.nft.fp <- function() {}
crypto.nft.fp_chart <- function() {}
crypto.nft.stats <- function() {}
crypto.nft.stats_chart <- function() {}
crypto.onchain.about <- function() {}
crypto.onchain.baas <- function() {}
crypto.onchain.baas_chart <- function() {}
crypto.onchain.balance <- function() {}
crypto.onchain.balance_chart <- function() {}
crypto.onchain.btc_supply <- function() {}
crypto.onchain.btc_supply_chart <- function() {}
crypto.onchain.btc_transac <- function() {}
crypto.onchain.btc_transac_chart <- function() {}
crypto.onchain.btcsingleblock <- function() {}
crypto.onchain.btcsingleblock_chart <- function() {}
crypto.onchain.dex_trades_monthly <- function() {}
crypto.onchain.dvcp <- function() {}
crypto.onchain.dvcp_chart <- function() {}
crypto.onchain.erc20_tokens <- function() {}
crypto.onchain.gwei <- function() {}
crypto.onchain.gwei_chart <- function() {}
crypto.onchain.hist <- function() {}
crypto.onchain.hist_chart <- function() {}
crypto.onchain.holders <- function() {}
crypto.onchain.holders_chart <- function() {}
crypto.onchain.hr <- function() {}
crypto.onchain.hr_chart <- function() {}
crypto.onchain.info <- function() {}
crypto.onchain.info_chart <- function() {}
crypto.onchain.lt <- function() {}
crypto.onchain.lt_chart <- function() {}
crypto.onchain.prices <- function() {}
crypto.onchain.prices_chart <- function() {}
crypto.onchain.query_graph <- function() {}
crypto.onchain.th <- function() {}
crypto.onchain.th_chart <- function() {}
crypto.onchain.token_decimals <- function() {}
crypto.onchain.top <- function() {}
crypto.onchain.top_chart <- function() {}
crypto.onchain.ttcp <- function() {}
crypto.onchain.ttcp_chart <- function() {}
crypto.onchain.tv <- function() {}
crypto.onchain.tv_chart <- function() {}
crypto.onchain.tx <- function() {}
crypto.onchain.tx_chart <- function() {}
crypto.onchain.ueat <- function() {}
crypto.onchain.ueat_chart <- function() {}
crypto.onchain.whales <- function() {}
crypto.onchain.whales_chart <- function() {}
crypto.ov.about <- function() {}
crypto.ov.altindex <- function() {}
crypto.ov.altindex_chart <- function() {}
crypto.ov.btcrb <- function() {}
crypto.ov.btcrb_chart <- function() {}
crypto.ov.categories <- function() {}
crypto.ov.categories_chart <- function() {}
crypto.ov.cbpairs <- function() {}
crypto.ov.cbpairs_chart <- function() {}
crypto.ov.coin_list <- function() {}
crypto.ov.contracts <- function() {}
crypto.ov.contracts_chart <- function() {}
crypto.ov.cr <- function() {}
crypto.ov.cr_chart <- function() {}
crypto.ov.crypto_hack <- function() {}
crypto.ov.crypto_hack_slugs <- function() {}
crypto.ov.crypto_hacks <- function() {}
crypto.ov.crypto_hacks_chart <- function() {}
crypto.ov.defi <- function() {}
crypto.ov.defi_chart <- function() {}
crypto.ov.derivatives <- function() {}
crypto.ov.derivatives_chart <- function() {}
crypto.ov.ewf <- function() {}
crypto.ov.ewf_chart <- function() {}
crypto.ov.exchanges <- function() {}
crypto.ov.exmarkets <- function() {}
crypto.ov.exmarkets_chart <- function() {}
crypto.ov.exrates <- function() {}
crypto.ov.exrates_chart <- function() {}
crypto.ov.globe <- function() {}
crypto.ov.hm <- function() {}
crypto.ov.hm_chart <- function() {}
crypto.ov.hold <- function() {}
crypto.ov.hold_chart <- function() {}
crypto.ov.indexes <- function() {}
crypto.ov.indexes_chart <- function() {}
crypto.ov.info <- function() {}
crypto.ov.info_chart <- function() {}
crypto.ov.markets <- function() {}
crypto.ov.markets_chart <- function() {}
crypto.ov.news <- function() {}
crypto.ov.news_chart <- function() {}
crypto.ov.platforms <- function() {}
crypto.ov.platforms_chart <- function() {}
crypto.ov.products <- function() {}
crypto.ov.products_chart <- function() {}
crypto.ov.stables <- function() {}
crypto.ov.stables_chart <- function() {}
crypto.ov.wf <- function() {}
crypto.ov.wf_chart <- function() {}
crypto.ov.wfpe <- function() {}
crypto.ov.wfpe_chart <- function() {}
crypto.tools.about <- function() {}
crypto.tools.apy <- function() {}
crypto.tools.apy_chart <- function() {}
crypto.tools.il <- function() {}
crypto.tools.il_chart <- function() {}
econometrics.about <- function() {}
econometrics.bgod <- function() {}
econometrics.bgod_chart <- function() {}
econometrics.bols <- function() {}
econometrics.bpag <- function() {}
econometrics.bpag_chart <- function() {}
econometrics.clean <- function() {}
econometrics.coint <- function() {}
econometrics.coint_chart <- function() {}
econometrics.comparison <- function() {}
econometrics.dwat <- function() {}
econometrics.dwat_chart <- function() {}
econometrics.fdols <- function() {}
econometrics.fe <- function() {}
econometrics.get_regression_data <- function() {}
econometrics.granger <- function() {}
econometrics.granger_chart <- function() {}
econometrics.load <- function() {}
econometrics.norm <- function() {}
econometrics.norm_chart <- function() {}
econometrics.ols <- function() {}
econometrics.options <- function() {}
econometrics.options_chart <- function() {}
econometrics.panel <- function() {}
econometrics.panel_chart <- function() {}
econometrics.pols <- function() {}
econometrics.re <- function() {}
econometrics.root <- function() {}
econometrics.root_chart <- function() {}
economy.about <- function() {}
economy.available_indices <- function() {}
economy.bigmac <- function() {}
economy.bigmac_chart <- function() {}
economy.country_codes <- function() {}
economy.cpi <- function() {}
economy.cpi_chart <- function() {}
economy.currencies <- function() {}
economy.events <- function() {}
economy.fred <- function() {}
economy.fred_chart <- function() {}
economy.fred_ids <- function() {}
economy.fred_notes <- function() {}
economy.future <- function() {}
economy.futures <- function() {}
economy.get_groups <- function() {}
economy.glbonds <- function() {}
economy.index <- function() {}
economy.index_chart <- function() {}
economy.indices <- function() {}
economy.macro <- function() {}
economy.macro_chart <- function() {}
economy.macro_countries <- function() {}
economy.macro_parameters <- function() {}
economy.overview <- function() {}
economy.perfmap <- function() {}
economy.performance <- function() {}
economy.rtps <- function() {}
economy.rtps_chart <- function() {}
economy.search_index <- function() {}
economy.spectrum <- function() {}
economy.treasury <- function() {}
economy.treasury_chart <- function() {}
economy.treasury_maturities <- function() {}
economy.usbonds <- function() {}
economy.valuation <- function() {}
etf.about <- function() {}
etf.candle <- function() {}
etf.compare <- function() {}
etf.etf_by_category <- function() {}
etf.etf_by_name <- function() {}
etf.holdings <- function() {}
etf.ld <- function() {}
etf.ln <- function() {}
etf.load <- function() {}
etf.news <- function() {}
etf.news_chart <- function() {}
etf.overview <- function() {}
etf.symbols <- function() {}
etf.weights <- function() {}
etf.disc.about <- function() {}
etf.disc.mover <- function() {}
fixedincome.about <- function() {}
fixedincome.ameribor <- function() {}
fixedincome.cp <- function() {}
fixedincome.dwpcr <- function() {}
fixedincome.ecb <- function() {}
fixedincome.ecbycrv <- function() {}
fixedincome.estr <- function() {}
fixedincome.fed <- function() {}
fixedincome.ffrmc <- function() {}
fixedincome.hqm <- function() {}
fixedincome.icebofa <- function() {}
fixedincome.icespread <- function() {}
fixedincome.iorb <- function() {}
fixedincome.moody <- function() {}
fixedincome.projection <- function() {}
fixedincome.sofr <- function() {}
fixedincome.sonia <- function() {}
fixedincome.spot <- function() {}
fixedincome.tbffr <- function() {}
fixedincome.tmc <- function() {}
fixedincome.treasury <- function() {}
fixedincome.usrates <- function() {}
fixedincome.ycrv <- function() {}
forecast.about <- function() {}
forecast.anom <- function() {}
forecast.anom_chart <- function() {}
forecast.atr <- function() {}
forecast.autoarima <- function() {}
forecast.autoarima_chart <- function() {}
forecast.autoces <- function() {}
forecast.autoces_chart <- function() {}
forecast.autoets <- function() {}
forecast.autoets_chart <- function() {}
forecast.autoselect <- function() {}
forecast.autoselect_chart <- function() {}
forecast.brnn <- function() {}
forecast.brnn_chart <- function() {}
forecast.clean <- function() {}
forecast.combine <- function() {}
forecast.corr <- function() {}
forecast.corr_chart <- function() {}
forecast.delete <- function() {}
forecast.delta <- function() {}
forecast.desc <- function() {}
forecast.desc_chart <- function() {}
forecast.ema <- function() {}
forecast.expo <- function() {}
forecast.expo_chart <- function() {}
forecast.export <- function() {}
forecast.linregr <- function() {}
forecast.linregr_chart <- function() {}
forecast.load <- function() {}
forecast.mom <- function() {}
forecast.mstl <- function() {}
forecast.mstl_chart <- function() {}
forecast.nbeats <- function() {}
forecast.nbeats_chart <- function() {}
forecast.nhits <- function() {}
forecast.nhits_chart <- function() {}
forecast.plot <- function() {}
forecast.plot_chart <- function() {}
forecast.regr <- function() {}
forecast.regr_chart <- function() {}
forecast.rename <- function() {}
forecast.rnn <- function() {}
forecast.rnn_chart <- function() {}
forecast.roc <- function() {}
forecast.rsi <- function() {}
forecast.rwd <- function() {}
forecast.rwd_chart <- function() {}
forecast.season_chart <- function() {}
forecast.seasonalnaive <- function() {}
forecast.seasonalnaive_chart <- function() {}
forecast.show <- function() {}
forecast.signal <- function() {}
forecast.sto <- function() {}
forecast.tcn <- function() {}
forecast.tcn_chart <- function() {}
forecast.tft <- function() {}
forecast.tft_chart <- function() {}
forecast.theta <- function() {}
forecast.theta_chart <- function() {}
forecast.trans <- function() {}
forecast.trans_chart <- function() {}
forecast.whisper <- function() {}
forex.about <- function() {}
forex.candle <- function() {}
forex.fwd <- function() {}
forex.get_currency_list <- function() {}
forex.load <- function() {}
forex.quote <- function() {}
forex.oanda.about <- function() {}
forex.oanda.calendar <- function() {}
forex.oanda.calendar_chart <- function() {}
forex.oanda.cancel <- function() {}
forex.oanda.cancel_chart <- function() {}
forex.oanda.candles <- function() {}
forex.oanda.candles_chart <- function() {}
forex.oanda.close <- function() {}
forex.oanda.close_chart <- function() {}
forex.oanda.listorders <- function() {}
forex.oanda.listorders_chart <- function() {}
forex.oanda.openpositions <- function() {}
forex.oanda.openpositions_chart <- function() {}
forex.oanda.opentrades <- function() {}
forex.oanda.opentrades_chart <- function() {}
forex.oanda.order <- function() {}
forex.oanda.order_chart <- function() {}
forex.oanda.orderbook <- function() {}
forex.oanda.orderbook_chart <- function() {}
forex.oanda.pending <- function() {}
forex.oanda.pending_chart <- function() {}
forex.oanda.positionbook <- function() {}
forex.oanda.positionbook_chart <- function() {}
forex.oanda.price <- function() {}
forex.oanda.price_chart <- function() {}
forex.oanda.summary <- function() {}
forex.oanda.summary_chart <- function() {}
futures.about <- function() {}
futures.curve <- function() {}
futures.curve_chart <- function() {}
futures.historical <- function() {}
futures.historical_chart <- function() {}
futures.search <- function() {}
keys.about <- function() {}
keys.av <- function() {}
keys.binance <- function() {}
keys.bitquery <- function() {}
keys.cmc <- function() {}
keys.coinbase <- function() {}
keys.coinglass <- function() {}
keys.cpanic <- function() {}
keys.databento <- function() {}
keys.degiro <- function() {}
keys.eodhd <- function() {}
keys.ethplorer <- function() {}
keys.finnhub <- function() {}
keys.fmp <- function() {}
keys.fred <- function() {}
keys.get_keys_info <- function() {}
keys.github <- function() {}
keys.glassnode <- function() {}
keys.messari <- function() {}
keys.mykeys <- function() {}
keys.news <- function() {}
keys.oanda <- function() {}
keys.openbb <- function() {}
keys.polygon <- function() {}
keys.quandl <- function() {}
keys.reddit <- function() {}
keys.rh <- function() {}
keys.santiment <- function() {}
keys.set_keys <- function() {}
keys.shroom <- function() {}
keys.smartstake <- function() {}
keys.stocksera <- function() {}
keys.tokenterminal <- function() {}
keys.tradier <- function() {}
keys.twitter <- function() {}
keys.walert <- function() {}
portfolio.about <- function() {}
portfolio.bench <- function() {}
portfolio.distr <- function() {}
portfolio.distr_chart <- function() {}
portfolio.dret <- function() {}
portfolio.dret_chart <- function() {}
portfolio.es <- function() {}
portfolio.holdp <- function() {}
portfolio.holdp_chart <- function() {}
portfolio.holdv <- function() {}
portfolio.holdv_chart <- function() {}
portfolio.load <- function() {}
portfolio.maxdd <- function() {}
portfolio.maxdd_chart <- function() {}
portfolio.mret <- function() {}
portfolio.mret_chart <- function() {}
portfolio.om <- function() {}
portfolio.om_chart <- function() {}
portfolio.perf <- function() {}
portfolio.rbeta <- function() {}
portfolio.rbeta_chart <- function() {}
portfolio.rsharpe <- function() {}
portfolio.rsharpe_chart <- function() {}
portfolio.rsort <- function() {}
portfolio.rsort_chart <- function() {}
portfolio.rvol <- function() {}
portfolio.rvol_chart <- function() {}
portfolio.show <- function() {}
portfolio.summary <- function() {}
portfolio.var <- function() {}
portfolio.yret <- function() {}
portfolio.yret_chart <- function() {}
portfolio.alloc.about <- function() {}
portfolio.alloc.assets <- function() {}
portfolio.alloc.countries <- function() {}
portfolio.alloc.regions <- function() {}
portfolio.alloc.sectors <- function() {}
portfolio.metric.about <- function() {}
portfolio.metric.calmar <- function() {}
portfolio.metric.commonsense <- function() {}
portfolio.metric.gaintopain <- function() {}
portfolio.metric.information <- function() {}
portfolio.metric.jensens <- function() {}
portfolio.metric.kelly <- function() {}
portfolio.metric.kurtosis <- function() {}
portfolio.metric.maxdrawdown <- function() {}
portfolio.metric.payoff <- function() {}
portfolio.metric.profitfactor <- function() {}
portfolio.metric.rsquare <- function() {}
portfolio.metric.sharpe <- function() {}
portfolio.metric.skew <- function() {}
portfolio.metric.sortino <- function() {}
portfolio.metric.tail <- function() {}
portfolio.metric.trackerr <- function() {}
portfolio.metric.volatility <- function() {}
portfolio.po.about <- function() {}
portfolio.po.blacklitterman <- function() {}
portfolio.po.ef <- function() {}
portfolio.po.ef_chart <- function() {}
portfolio.po.file <- function() {}
portfolio.po.herc <- function() {}
portfolio.po.hrp <- function() {}
portfolio.po.load <- function() {}
portfolio.po.load_bl_views <- function() {}
portfolio.po.maxdecorr <- function() {}
portfolio.po.maxdiv <- function() {}
portfolio.po.maxret <- function() {}
portfolio.po.maxsharpe <- function() {}
portfolio.po.maxutil <- function() {}
portfolio.po.minrisk <- function() {}
portfolio.po.nco <- function() {}
portfolio.po.plot <- function() {}
portfolio.po.plot_chart <- function() {}
portfolio.po.relriskparity <- function() {}
portfolio.po.riskparity <- function() {}
portfolio.po.show <- function() {}
qa.about <- function() {}
qa.acf <- function() {}
qa.bw <- function() {}
qa.calculate_adjusted_var <- function() {}
qa.cdf <- function() {}
qa.cusum <- function() {}
qa.decompose <- function() {}
qa.es <- function() {}
qa.es_chart <- function() {}
qa.hist <- function() {}
qa.kurtosis <- function() {}
qa.kurtosis_chart <- function() {}
qa.line <- function() {}
qa.normality <- function() {}
qa.normality_chart <- function() {}
qa.omega <- function() {}
qa.omega_chart <- function() {}
qa.qqplot <- function() {}
qa.quantile <- function() {}
qa.quantile_chart <- function() {}
qa.rolling <- function() {}
qa.rolling_chart <- function() {}
qa.sharpe <- function() {}
qa.sharpe_chart <- function() {}
qa.skew <- function() {}
qa.skew_chart <- function() {}
qa.sortino <- function() {}
qa.sortino_chart <- function() {}
qa.spread <- function() {}
qa.spread_chart <- function() {}
qa.summary <- function() {}
qa.summary_chart <- function() {}
qa.unitroot <- function() {}
qa.unitroot_chart <- function() {}
qa.var <- function() {}
qa.var_chart <- function() {}
stocks.about <- function() {}
stocks.candle <- function() {}
stocks.load <- function() {}
stocks.process_candle <- function() {}
stocks.quote <- function() {}
stocks.search <- function() {}
stocks.tob <- function() {}
stocks.ba.about <- function() {}
stocks.ba.bullbear <- function() {}
stocks.ba.cnews <- function() {}
stocks.ba.getdd <- function() {}
stocks.ba.headlines <- function() {}
stocks.ba.headlines_chart <- function() {}
stocks.ba.infer <- function() {}
stocks.ba.infer_chart <- function() {}
stocks.ba.mentions <- function() {}
stocks.ba.mentions_chart <- function() {}
stocks.ba.messages <- function() {}
stocks.ba.popular <- function() {}
stocks.ba.queries <- function() {}
stocks.ba.redditsent <- function() {}
stocks.ba.regions <- function() {}
stocks.ba.regions_chart <- function() {}
stocks.ba.rise <- function() {}
stocks.ba.sentiment <- function() {}
stocks.ba.sentiment_chart <- function() {}
stocks.ba.snews <- function() {}
stocks.ba.snews_chart <- function() {}
stocks.ba.spac <- function() {}
stocks.ba.spacc <- function() {}
stocks.ba.stalker <- function() {}
stocks.ba.text_sent <- function() {}
stocks.ba.trending <- function() {}
stocks.ba.watchlist <- function() {}
stocks.ba.wsb <- function() {}
stocks.ca.about <- function() {}
stocks.ca.balance <- function() {}
stocks.ca.cashflow <- function() {}
stocks.ca.hcorr <- function() {}
stocks.ca.hcorr_chart <- function() {}
stocks.ca.hist <- function() {}
stocks.ca.hist_chart <- function() {}
stocks.ca.income <- function() {}
stocks.ca.income_chart <- function() {}
stocks.ca.scorr <- function() {}
stocks.ca.scorr_chart <- function() {}
stocks.ca.screener <- function() {}
stocks.ca.sentiment <- function() {}
stocks.ca.sentiment_chart <- function() {}
stocks.ca.similar <- function() {}
stocks.ca.volume <- function() {}
stocks.ca.volume_chart <- function() {}
stocks.disc.about <- function() {}
stocks.disc.active <- function() {}
stocks.disc.arkord <- function() {}
stocks.disc.asc <- function() {}
stocks.disc.dividends <- function() {}
stocks.disc.filings <- function() {}
stocks.disc.filings_chart <- function() {}
stocks.disc.fipo <- function() {}
stocks.disc.gainers <- function() {}
stocks.disc.gtech <- function() {}
stocks.disc.hotpenny <- function() {}
stocks.disc.ipo <- function() {}
stocks.disc.losers <- function() {}
stocks.disc.lowfloat <- function() {}
stocks.disc.news <- function() {}
stocks.disc.pipo <- function() {}
stocks.disc.rtat <- function() {}
stocks.disc.trending <- function() {}
stocks.disc.ugs <- function() {}
stocks.disc.ulc <- function() {}
stocks.disc.upcoming <- function() {}
stocks.dps.about <- function() {}
stocks.dps.ctb <- function() {}
stocks.dps.dpotc <- function() {}
stocks.dps.dpotc_chart <- function() {}
stocks.dps.ftd <- function() {}
stocks.dps.ftd_chart <- function() {}
stocks.dps.hsi <- function() {}
stocks.dps.pos <- function() {}
stocks.dps.prom <- function() {}
stocks.dps.prom_chart <- function() {}
stocks.dps.psi_q <- function() {}
stocks.dps.psi_q_chart <- function() {}
stocks.dps.psi_sg <- function() {}
stocks.dps.psi_sg_chart <- function() {}
stocks.dps.shorted <- function() {}
stocks.dps.sidtc <- function() {}
stocks.dps.spos <- function() {}
stocks.dps.spos_chart <- function() {}
stocks.fa.about <- function() {}
stocks.fa.analysis <- function() {}
stocks.fa.analyst <- function() {}
stocks.fa.balance <- function() {}
stocks.fa.cal <- function() {}
stocks.fa.cash <- function() {}
stocks.fa.customer <- function() {}
stocks.fa.data <- function() {}
stocks.fa.dcf <- function() {}
stocks.fa.dcfc <- function() {}
stocks.fa.divs <- function() {}
stocks.fa.divs_chart <- function() {}
stocks.fa.dupont <- function() {}
stocks.fa.earnings <- function() {}
stocks.fa.enterprise <- function() {}
stocks.fa.epsfc <- function() {}
stocks.fa.est <- function() {}
stocks.fa.fama_coe <- function() {}
stocks.fa.fama_raw <- function() {}
stocks.fa.fraud <- function() {}
stocks.fa.growth <- function() {}
stocks.fa.historical_5 <- function() {}
stocks.fa.income <- function() {}
stocks.fa.info <- function() {}
stocks.fa.key <- function() {}
stocks.fa.metrics <- function() {}
stocks.fa.mgmt <- function() {}
stocks.fa.mktcap <- function() {}
stocks.fa.mktcap_chart <- function() {}
stocks.fa.news <- function() {}
stocks.fa.overview <- function() {}
stocks.fa.profile <- function() {}
stocks.fa.pt <- function() {}
stocks.fa.pt_chart <- function() {}
stocks.fa.rating <- function() {}
stocks.fa.ratios <- function() {}
stocks.fa.revfc <- function() {}
stocks.fa.rot <- function() {}
stocks.fa.rot_chart <- function() {}
stocks.fa.score <- function() {}
stocks.fa.sec <- function() {}
stocks.fa.sec_fmp <- function() {}
stocks.fa.sec_fmp_chart <- function() {}
stocks.fa.shrs <- function() {}
stocks.fa.similar_dfs <- function() {}
stocks.fa.splits <- function() {}
stocks.fa.splits_chart <- function() {}
stocks.fa.supplier <- function() {}
stocks.gov.about <- function() {}
stocks.gov.contracts <- function() {}
stocks.gov.contracts_chart <- function() {}
stocks.gov.government_trading <- function() {}
stocks.gov.gtrades <- function() {}
stocks.gov.gtrades_chart <- function() {}
stocks.gov.histcont <- function() {}
stocks.gov.histcont_chart <- function() {}
stocks.gov.lastcontracts <- function() {}
stocks.gov.lastcontracts_chart <- function() {}
stocks.gov.lasttrades <- function() {}
stocks.gov.lobbying <- function() {}
stocks.gov.qtrcontracts <- function() {}
stocks.gov.qtrcontracts_chart <- function() {}
stocks.gov.topbuys <- function() {}
stocks.gov.topbuys_chart <- function() {}
stocks.gov.toplobbying <- function() {}
stocks.gov.toplobbying_chart <- function() {}
stocks.gov.topsells <- function() {}
stocks.gov.topsells_chart <- function() {}
stocks.ins.about <- function() {}
stocks.ins.act <- function() {}
stocks.ins.act_chart <- function() {}
stocks.ins.blcp <- function() {}
stocks.ins.blcs <- function() {}
stocks.ins.blip <- function() {}
stocks.ins.blis <- function() {}
stocks.ins.blop <- function() {}
stocks.ins.blos <- function() {}
stocks.ins.filter <- function() {}
stocks.ins.lcb <- function() {}
stocks.ins.lins <- function() {}
stocks.ins.lins_chart <- function() {}
stocks.ins.lip <- function() {}
stocks.ins.lis <- function() {}
stocks.ins.lit <- function() {}
stocks.ins.lpsb <- function() {}
stocks.ins.print_insider_data <- function() {}
stocks.ins.print_insider_data_chart <- function() {}
stocks.ins.stats <- function() {}
stocks.options.about <- function() {}
stocks.options.chains <- function() {}
stocks.options.dte <- function() {}
stocks.options.eodchain <- function() {}
stocks.options.expirations <- function() {}
stocks.options.generate_data <- function() {}
stocks.options.greeks <- function() {}
stocks.options.grhist <- function() {}
stocks.options.grhist_chart <- function() {}
stocks.options.hist <- function() {}
stocks.options.info <- function() {}
stocks.options.info_chart <- function() {}
stocks.options.last_price <- function() {}
stocks.options.oi <- function() {}
stocks.options.pcr <- function() {}
stocks.options.pcr_chart <- function() {}
stocks.options.price <- function() {}
stocks.options.unu <- function() {}
stocks.options.unu_chart <- function() {}
stocks.options.voi <- function() {}
stocks.options.vol <- function() {}
stocks.options.vsurf <- function() {}
stocks.options.vsurf_chart <- function() {}
stocks.qa.about <- function() {}
stocks.qa.beta <- function() {}
stocks.qa.beta_chart <- function() {}
stocks.qa.capm <- function() {}
stocks.qa.fama_raw <- function() {}
stocks.qa.historical_5 <- function() {}
stocks.screener.about <- function() {}
stocks.screener.arktrades <- function() {}
stocks.screener.historical <- function() {}
stocks.screener.historical_chart <- function() {}
stocks.screener.screener_data <- function() {}
stocks.screener.screener_data_chart <- function() {}
stocks.ta.about <- function() {}
stocks.ta.recom <- function() {}
stocks.ta.recom_chart <- function() {}
stocks.ta.rsp <- function() {}
stocks.ta.rsp_chart <- function() {}
stocks.ta.summary <- function() {}
stocks.ta.summary_chart <- function() {}
stocks.ta.view <- function() {}
stocks.ta.view_chart <- function() {}
stocks.th.about <- function() {}
stocks.th.all <- function() {}
stocks.th.all_chart <- function() {}
stocks.th.check_if_open <- function() {}
stocks.th.closed <- function() {}
stocks.th.closed_chart <- function() {}
stocks.th.exchange <- function() {}
stocks.th.exchange_chart <- function() {}
stocks.th.open <- function() {}
stocks.th.open_chart <- function() {}
ta.about <- function() {}
ta.ad <- function() {}
ta.ad_chart <- function() {}
ta.adosc <- function() {}
ta.adosc_chart <- function() {}
ta.adx <- function() {}
ta.adx_chart <- function() {}
ta.aroon <- function() {}
ta.aroon_chart <- function() {}
ta.atr <- function() {}
ta.atr_chart <- function() {}
ta.bbands <- function() {}
ta.bbands_chart <- function() {}
ta.cci <- function() {}
ta.cci_chart <- function() {}
ta.cg <- function() {}
ta.cg_chart <- function() {}
ta.clenow <- function() {}
ta.clenow_chart <- function() {}
ta.cones <- function() {}
ta.cones_chart <- function() {}
ta.demark <- function() {}
ta.demark_chart <- function() {}
ta.donchian <- function() {}
ta.donchian_chart <- function() {}
ta.ema <- function() {}
ta.fib <- function() {}
ta.fib_chart <- function() {}
ta.fisher <- function() {}
ta.fisher_chart <- function() {}
ta.hma <- function() {}
ta.kc <- function() {}
ta.kc_chart <- function() {}
ta.ma <- function() {}
ta.ma_chart <- function() {}
ta.macd <- function() {}
ta.macd_chart <- function() {}
ta.obv <- function() {}
ta.obv_chart <- function() {}
ta.rsi <- function() {}
ta.rsi_chart <- function() {}
ta.rvol_garman_klass <- function() {}
ta.rvol_hodges_tompkins <- function() {}
ta.rvol_parkinson <- function() {}
ta.rvol_rogers_satchell <- function() {}
ta.rvol_std <- function() {}
ta.rvol_yang_zhang <- function() {}
ta.sma <- function() {}
ta.standard_deviation <- function() {}
ta.stoch <- function() {}
ta.stoch_chart <- function() {}
ta.vwap <- function() {}
ta.vwap_chart <- function() {}
ta.wma <- function() {}
ta.zlma <- function() {}
